In [13]:
# --- en la primera celda del notebook
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [14]:

import sys
from pathlib import Path

# añade la carpeta raíz del proyecto al sys.path
PROJECT_ROOT = Path.cwd()   # si la nb está junto a "portafolios/"

In [32]:
from portafolios.core.portafolio import Portfolio
from portafolios.data.local_loader import local_loader
from portafolios.constructores.naive import Naive
from portafolios.constructores.markowitz import Markowitz

In [16]:


csv_path = "data_clean_stock_data.csv"

# loader que ignora tickers/start/end y lee TU csv
loader_from_csv = lambda *args, **kwargs: local_loader(*args, **kwargs, path=csv_path)

p = (Portfolio(
        tickers=None,
        start="2019-01-01",
        end="2019-12-31",
        loader=local_loader,
        loader_kwargs={"path": csv_path, "prefer_adj_close": True},
        freq="B",
     )
     .preparar_datos()
                  # ← capa de métricas por activo
)

In [17]:
print("Tickers:", p.tickers[:10])   # muestra algunos
p.prices.head()

Tickers: ['AAPL', 'ABBV', '0ABT', '0ACN', 'ADBE', '0AMD', 'AMGN', 'AMZN', 'AVGO', '0BAC']

,AAPL,ABBV,0ABT,0ACN,ADBE,0AMD,AMGN,AMZN,AVGO,0BAC,...,0TMO,TSLA,0TXN,0UNH,0UPS,000V,00VZ,0WFC,0WMT,0XOM
Date,,,,,,,,,,,,,,,,,,,,,
2019-01-02,37.889009,69.054458,63.640057,129.554251,226.169998,19.000000,159.660719,77.667999,21.292662,21.706751,...,218.074143,21.008667,80.026357,225.088476,78.025968,128.060076,40.179978,39.319736,28.386662,51.853457
2019-01-03,34.757238,67.193050,61.774625,128.067714,223.630005,18.680000,160.470578,76.900002,20.610491,21.620407,...,215.817447,20.626667,77.959528,222.466198,77.456938,125.704545,40.773809,39.654730,28.707961,52.135471
2019-01-04,35.432248,67.450306,61.505575,129.691815,227.649994,19.070000,162.404371,79.699997,19.766979,22.147104,...,221.257239,21.200001,78.455227,222.447926,78.482769,128.874011,40.702261,40.291216,28.389689,52.892448
2019-01-07,35.499034,68.676139,62.653528,130.636997,232.600006,20.680000,164.751309,81.727997,20.083820,22.259350,...,225.139994,22.449333,80.001150,221.095616,78.659079,131.344430,40.966979,40.391716,28.847388,53.508427
2019-01-08,36.212212,69.841416,62.456216,134.711035,233.770004,21.200001,166.205762,83.830498,20.222587,22.267985,...,227.702170,22.934000,80.354028,223.663082,79.428432,132.321094,41.990081,40.333103,29.026229,53.872080

In [18]:
p.asset_log_returns

,AAPL,ABBV,0ABT,0ACN,ADBE,0AMD,AMGN,AMZN,AVGO,0BAC,...,0TMO,TSLA,0TXN,0UNH,0UPS,000V,00VZ,0WFC,0WMT,0XOM
Date,,,,,,,,,,,,,,,,,,,,,
2019-01-03,-0.086273,-0.027326,-0.029750,-0.011541,-0.011294,-0.016986,0.005060,-0.009937,-0.032562,-0.003986,...,-0.010402,-0.018350,-0.026166,-1.171838e-02,-0.007320,-0.018565,0.014671,0.008484,0.011255,5.423923e-03
2019-01-04,0.019235,0.003821,-0.004365,0.012602,0.017816,0.020663,0.011979,0.035764,-0.041787,0.024069,...,0.024893,0.027416,0.006338,-8.213654e-05,0.013157,0.024901,-0.001756,0.015923,-0.011148,1.441503e-02
2019-01-07,0.001883,0.018011,0.018492,0.007261,0.021511,0.081051,0.014348,0.025127,0.015902,0.005055,...,0.017396,0.057260,0.019513,-6.097773e-03,0.002244,0.018988,0.006483,0.002491,0.015993,1.157860e-02
2019-01-08,0.019891,0.016825,-0.003154,0.030710,0.005017,0.024834,0.008789,0.025400,0.006886,0.000388,...,0.011316,0.021360,0.004401,1.154556e-02,0.009733,0.007408,0.024667,-0.001452,0.006180,6.773183e-03
2019-01-09,0.017693,-0.009908,0.003011,0.002653,0.020409,0.011257,0.008812,-0.005268,0.019568,0.002324,...,0.030013,-0.001484,0.008848,7.488564e-03,-0.007901,0.009291,-0.006283,-0.003745,0.003961,1.377284e-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-12-25,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00
2019-12-26,0.017709,0.003534,0.000457,0.002124,-0.000785,0.014907,0.002219,0.040862,0.003300,0.007905,...,-0.006862,0.018651,-0.000776,1.452351e-03,0.007323,0.006150,-0.001466,0.006456,0.002088,2.540568e-07
2019-12-27,0.013665,-0.004862,0.002625,0.002401,0.004818,-0.009131,-0.002671,0.016406,-0.007456,0.004490,...,0.002628,0.004213,0.001319,9.451071e-04,0.002178,0.003746,0.004066,-0.001288,0.000750,-2.698822e-03
2019-12-30,-0.004364,-0.006111,0.000456,-0.001836,-0.007266,-0.015261,-0.000042,-0.009193,-0.006346,-0.001962,...,-0.000733,-0.014601,-0.003496,-2.342954e-07,-0.002262,-0.002161,0.001135,-0.001105,-0.001084,1.847331e-03
2019-12-31,0.003377,-0.012673,-0.009154,-0.005575,-0.001605,-0.001734,-0.006275,-0.016451,-0.003061,-0.011000,...,-0.006650,-0.018135,-0.000623,-8.296109e-03,-0.018028,-0.007841,-0.004712,-0.008142,-0.000083,-9.127464e-03

In [19]:
p.construir(Naive())  
p.weights

000V    0.020408
00HD    0.020408
00KO    0.020408
00MA    0.020408
00PG    0.020408
00PM    0.020408
00VZ    0.020408
0ABT    0.020408
0ACN    0.020408
0AMD    0.020408
0BAC    0.020408
0BMY    0.020408
0CRM    0.020408
0CVX    0.020408
0DHR    0.020408
0DIS    0.020408
0HON    0.020408
0JPM    0.020408
0LIN    0.020408
0LLY    0.020408
0MCD    0.020408
0MRK    0.020408
0NEE    0.020408
0NKE    0.020408
0PEP    0.020408
0PFE    0.020408
0TMO    0.020408
0TXN    0.020408
0UNH    0.020408
0UPS    0.020408
0WFC    0.020408
0WMT    0.020408
0XOM    0.020408
AAPL    0.020408
ABBV    0.020408
ADBE    0.020408
AMGN    0.020408
AMZN    0.020408
AVGO    0.020408
COST    0.020408
CSCO    0.020408
GOOG    0.020408
INTC    0.020408
META    0.020408
MSFT    0.020408
NFLX    0.020408
NVDA    0.020408
ORCL    0.020408
TSLA    0.020408
dtype: float64

In [20]:
# KPIs por momentos (per-period por defecto)
p.kpi("exp_return")

0.001183347468500027

In [21]:
p.kpi("vol")

np.float64(0.006895915240408382)

In [22]:
p.kpi('cvar')

0.0

In [23]:
p.kpi("sharpe_m", rf_per_period=0.0, ann_factor=252)

np.float64(2.7240849172996793)

In [24]:
# Resumen básico
p.kpis_basicos(ann_factor=252, rf_per_period=0.0)

{'expected_return': 0.29820356206200677,
 'volatility': np.float64(0.10946926072980462),
 'sharpe_m': np.float64(2.7240849172996793)}

In [25]:
p.kpis_basicos(rf_per_period=0.0)

{'expected_return': 0.001183347468500027,
 'volatility': np.float64(0.006895915240408382),
 'sharpe_m': np.float64(0.1716012200332596)}

In [29]:
p.barras()

Gráfica de barras guardada en: c:\Users\narro\Desktop\semestre\honores_actuaria\plots\portfolio_barras_naive_1_over_n.html

In [28]:
p.bubbleplot()

Bubble plot guardado en:
c:\Users\narro\Desktop\semestre\honores_actuaria\plots\bubble_plot_naive_1_over_n.html

In [31]:
p.corr_heatmap()

Heatmap de Correlación guardado en:
c:\Users\narro\Desktop\semestre\honores_actuaria\plots\heatmap_corr_naive_1_over_n.html

In [33]:


mk = Markowitz(rf_per_period=0.0)

# 1) Versión "teoría" (default) usando log(1 + r_simple)
p.construir(mk)                 # ret_kind="log" por default

# 2) Versión usando retornos simples tal cual
p.construir(mk, ret_kind="simple")

# y luego:
p.kpis_basicos(ann_factor=252, rf_per_period=0.0)
p.pastel()
p.barras()
p.bubbleplot()

Gráfica de pastel guardada en: c:\Users\narro\Desktop\semestre\honores_actuaria\plots\portfolio_pastel_markowitz_max_sharpe.html
Gráfica de barras guardada en: c:\Users\narro\Desktop\semestre\honores_actuaria\plots\portfolio_barras_markowitz_max_sharpe.html

Bubble plot guardado en:
c:\Users\narro\Desktop\semestre\honores_actuaria\plots\bubble_plot_markowitz_max_sharpe.html

In [ ]:
from pathlib import Path
import webbrowser

# Carpeta donde están todos tus HTML
BASE_PATH = Path(r"c:\Users\narro\Desktop\semestre\honores_actuaria\plots")

def ver_html(nombre_archivo: str):
    """
    Abre en el navegador un archivo HTML ubicado en la carpeta BASE_PATH.
    Parámetros:
        nombre_archivo (str): nombre del archivo HTML, ej: 'grafica.html'
    """
    ruta = BASE_PATH / nombre_archivo
    if not ruta.exists():
        raise FileNotFoundError(f"No se encontró el archivo: {ruta}")

    url = ruta.resolve().as_uri()
    webbrowser.open(url)
    print(f"Abriendo: {url}")

In [ ]:
#ver_html("portfolio_pastel_naive_1_over_n.html")

medidas 
que podemos hacer a demas de correlacion 
finanzas vs correlacion