In [1]:
# --- en la primera celda del notebook
%load_ext autoreload
%autoreload 2

In [2]:

import sys
from pathlib import Path

# añade la carpeta raíz del proyecto al sys.path
PROJECT_ROOT = Path.cwd()   # si la nb está junto a "portafolios/"

In [ ]:
import portafolios
from portafolios.core.portafolio import Portfolio
from portafolios.data.local_loader import local_loader
#from portafolios.constructores.naive import Naive
form portafolios.constructores.equal_risk_contribution import EqualRiskContribution
from portafolios.constructores.markowitz import Markowitz
from portafolios.data import portfolio_loader

ImportError: cannot import name 'portfolio_loader' from 'portafolios.data' (unknown location)

In [10]:
from portafolios.data.yfinance_loader import yfinance_loader

df = yfinance_loader(
    tickers=["AAPL", "MSFT"],
    start="2024-01-01",
    end="2024-01-10",
)
df.preparar_datos()

print(df)

AttributeError: 'DataFrame' object has no attribute 'preparar_datos'

In [8]:
from portafolios.data.yfinance_loader import yfinance_loader
from portafolios.core.portafolio import Portfolio

py = Portfolio(
    tickers=["AAPL", "MSFT", "AMZN"],
    start="2015-01-01",
    end="2025-01-01",
    loader=yfinance_loader,
    loader_kwargs={"batch_size": 100, "prefer_adj_close": True},
)
py.preparar_datos()

3 Failed downloads:
['AAPL', 'MSFT', 'AMZN']: ValueError('unconverted data remains: T00:00:00')

ValueError: Yahoo Finance no devolvio datos para los tickers solicitados.

In [5]:


csv_path = "data_clean_stock_data.csv"

# loader que ignora tickers/start/end y lee TU csv
loader_from_csv = lambda *args, **kwargs: local_loader(*args, **kwargs, path=csv_path)

p = (Portfolio(
        tickers=None,
        start="2019-01-01",
        end="2019-12-31",
        loader=local_loader,
        loader_kwargs={"path": csv_path, "prefer_adj_close": True},
        freq="B",
     )
     .preparar_datos()
                  # ← capa de métricas por activo
)

In [6]:
print("Tickers:", p.tickers[:10])   # muestra algunos
p.prices.head()

Tickers: ['AAPL', 'ABBV', '0ABT', '0ACN', 'ADBE', '0AMD', 'AMGN', 'AMZN', 'AVGO', '0BAC']

                 AAPL       ABBV       0ABT  ...       0WFC       0WMT       0XOM
Date                                         ...
2019-01-02  37.889009  69.054458  63.640057  ...  39.319736  28.386662  51.853457
2019-01-03  34.757238  67.193050  61.774625  ...  39.654730  28.707961  52.135471
2019-01-04  35.432248  67.450306  61.505575  ...  40.291216  28.389689  52.892448
2019-01-07  35.499034  68.676139  62.653528  ...  40.391716  28.847388  53.508427
2019-01-08  36.212212  69.841416  62.456216  ...  40.333103  29.026229  53.872080

[5 rows x 49 columns]

In [7]:
p.asset_log_returns

                AAPL      ABBV      0ABT  ...      0WFC      0WMT          0XOM
Date                                      ...
2019-01-03 -0.086273 -0.027326 -0.029750  ...  0.008484  0.011255  5.423923e-03
2019-01-04  0.019235  0.003821 -0.004365  ...  0.015923 -0.011148  1.441503e-02
2019-01-07  0.001883  0.018011  0.018492  ...  0.002491  0.015993  1.157860e-02
2019-01-08  0.019891  0.016825 -0.003154  ... -0.001452  0.006180  6.773183e-03
2019-01-09  0.017693 -0.009908  0.003011  ... -0.003745  0.003961  1.377284e-04
...              ...       ...       ...  ...       ...       ...           ...
2019-12-25  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000e+00
2019-12-26  0.017709  0.003534  0.000457  ...  0.006456  0.002088  2.540568e-07
2019-12-27  0.013665 -0.004862  0.002625  ... -0.001288  0.000750 -2.698822e-03
2019-12-30 -0.004364 -0.006111  0.000456  ... -0.001105 -0.001084  1.847331e-03
2019-12-31  0.003377 -0.012673 -0.009154  ... -0.008142 -0.000083 -9.127464e-03

[259 rows x 49 columns]

In [8]:
p.construir(Naive())  
p.weights

000V    0.020408
00HD    0.020408
00KO    0.020408
00MA    0.020408
00PG    0.020408
00PM    0.020408
00VZ    0.020408
0ABT    0.020408
0ACN    0.020408
0AMD    0.020408
0BAC    0.020408
0BMY    0.020408
0CRM    0.020408
0CVX    0.020408
0DHR    0.020408
0DIS    0.020408
0HON    0.020408
0JPM    0.020408
0LIN    0.020408
0LLY    0.020408
0MCD    0.020408
0MRK    0.020408
0NEE    0.020408
0NKE    0.020408
0PEP    0.020408
0PFE    0.020408
0TMO    0.020408
0TXN    0.020408
0UNH    0.020408
0UPS    0.020408
0WFC    0.020408
0WMT    0.020408
0XOM    0.020408
AAPL    0.020408
ABBV    0.020408
ADBE    0.020408
AMGN    0.020408
AMZN    0.020408
AVGO    0.020408
COST    0.020408
CSCO    0.020408
GOOG    0.020408
INTC    0.020408
META    0.020408
MSFT    0.020408
NFLX    0.020408
NVDA    0.020408
ORCL    0.020408
TSLA    0.020408
dtype: float64

In [9]:
# KPIs por momentos (per-period por defecto)
p.kpi("exp_return")

0.001183347468500027

In [10]:
p.kpi("vol")

np.float64(0.006895915240408382)

In [11]:
p.kpi('cvar')

0.0

In [12]:
p.kpi("sharpe_m", rf_per_period=0.0, ann_factor=252)

np.float64(2.7240849172996793)

In [13]:
# Resumen básico
p.kpis_basicos(ann_factor=252, rf_per_period=0.0)

{'expected_return': 0.29820356206200677,
 'volatility': np.float64(0.10946926072980462),
 'sharpe_m': np.float64(2.7240849172996793)}

In [14]:
p.kpis_basicos(rf_per_period=0.0)

{'expected_return': 0.001183347468500027,
 'volatility': np.float64(0.006895915240408382),
 'sharpe_m': np.float64(0.1716012200332596)}

In [15]:
p.barras()

Gráfica de barras guardada en: c:\Users\narro\Desktop\semestre\honores_actuaria\plots\portfolio_barras_naive_1_over_n.html

In [16]:
p.bubbleplot()

Bubble plot guardado en:
c:\Users\narro\Desktop\semestre\honores_actuaria\plots\bubble_plot_naive_1_over_n.html

In [17]:
p.corr_heatmap()

Heatmap de Correlación guardado en:
c:\Users\narro\Desktop\semestre\honores_actuaria\plots\heatmap_corr_naive_1_over_n.html

In [18]:


mk = Markowitz(rf_per_period=0.0)

# 1) Versión "teoría" (default) usando log(1 + r_simple)
p.construir(mk)                 # ret_kind="log" por default

# 2) Versión usando retornos simples tal cual
p.construir(mk, ret_kind="simple")

# y luego:
p.kpis_basicos(ann_factor=252, rf_per_period=0.0)
p.pastel()
p.barras()
p.bubbleplot()

Gráfica de pastel guardada en: c:\Users\narro\Desktop\semestre\honores_actuaria\plots\portfolio_pastel_markowitz_max_sharpe.html
Gráfica de barras guardada en: c:\Users\narro\Desktop\semestre\honores_actuaria\plots\portfolio_barras_markowitz_max_sharpe.html

Bubble plot guardado en:
c:\Users\narro\Desktop\semestre\honores_actuaria\plots\bubble_plot_markowitz_max_sharpe.html

In [19]:
from pathlib import Path
import webbrowser

# Carpeta donde están todos tus HTML
BASE_PATH = Path(r"c:\Users\narro\Desktop\semestre\honores_actuaria\plots")

def ver_html(nombre_archivo: str):
    """
    Abre en el navegador un archivo HTML ubicado en la carpeta BASE_PATH.
    Parámetros:
        nombre_archivo (str): nombre del archivo HTML, ej: 'grafica.html'
    """
    ruta = BASE_PATH / nombre_archivo
    if not ruta.exists():
        raise FileNotFoundError(f"No se encontró el archivo: {ruta}")

    url = ruta.resolve().as_uri()
    webbrowser.open(url)
    print(f"Abriendo: {url}")

In [20]:
#ver_html("portfolio_pastel_naive_1_over_n.html")

medidas 
que podemos hacer a demas de correlacion 
finanzas vs correlacion

In [21]:
from portafolios.constructores.hrp_style.hrp_core import HRPStyle



hrp = HRPStyle(
    distance="deprado",
    clustering="hierarchical",
    inner=Naive(),  
    outer=Naive(), 
    n_clusters=3,
)

p.construir(hrp)    # igualito que p.construir(mk)

In [22]:
p.plot_hrp_matriz_distancias(file_path="hrp_matriz_distancias_deprado.html")

In [23]:
p.plot_hrp_hist_distancias()

In [24]:
matriz_de_dist = p.get_hrp_dist_matrix()

In [25]:
matriz_de_dist.to_csv("matriz_de_distancias_de_prado.csv")

In [26]:
from portafolios.constructores.hrp_style.hrp_core import HRPStyle
from portafolios.constructores.naive_risk_parity import NaiveRiskParity


hrp = HRPStyle(
    distance="deprado",
    clustering="hierarchical",
    inner=NaiveRiskParity(),  
    outer=NaiveRiskParity(), 
    n_clusters=3,
)

p.construir(hrp)    # igualito que p.construir(mk)

In [27]:
from portafolios.core.portafolio import Portfolio
from portafolios.constructores.hrp_style.hrp_recursive import HRPRecursive


hrp_rec = HRPRecursive(
    distance="deprado",          # o "corr"
    clustering="hierarchical",
)

p.construir(hrp_rec)

p.weights      # pesos HRP recursivos
p.barras()    # tus métricas normales

Gráfica de barras guardada en: c:\Users\narro\Desktop\semestre\honores_actuaria\plots\portfolio_barras_HRP-recursive.html